title: Dmitry Yutkin blog
email: yutkinn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Different thoughts about computer science, machine learning, programming
  and my personal life.
baseurl: ""
url: "http://yutkin.github.io"
twitter_username: yutkinn
github_username:  yutkin

# Build settings
theme: minima
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
